// Yeh file development ke liye local data source ke roop mein mock product catalogue provide karti hai.
import type { Product } from "./products.types";

/**
 * Yeh storefront ke liye temporary in-memory catalogue provide karta hai.
 * Production mein is data ko normally API se fetch kiya jata hai.
 */
export const mockProducts: Product[] = [
  {
    id: "wxw-001",
    title: "Midnight Wax",
    artist: "The Low Static",
    genre: "Jazz",
    price: 28.5,
    year: 1997,
    stock: 6,
    format: "LP",
    labelColor: "#D98E04",
    ringColor: "#7A4A12",
    description:
      "A smoky late-night session cut in one take. Warm upright bass, brushed drums.",
  },
  {
    id: "wxw-002",
    title: "Concrete Bloom",
    artist: "Ferra & The Kites",
    genre: "Indie",
    price: 24.0,
    year: 2016,
    stock: 12,
    format: "LP",
    labelColor: "#5C6B4E",
    ringColor: "#33402A",
    description: "Jangly guitars over a driving rhythm section. Summer in a sleeve.",
  },
  {
    id: "wxw-003",
    title: "Third Rail",
    artist: "Nova Terrace",
    genre: "Electronic",
    price: 31.0,
    year: 2021,
    stock: 3,
    format: "LP",
    labelColor: "#8C2F1B",
    ringColor: "#4A160D",
    description: "Analog synths, four-on-the-floor pulse, one long crescendo.",
  },
  {
    id: "wxw-004",
    title: "Slow Burn",
    artist: "Odessa Grove",
    genre: "Soul",
    price: 26.5,
    year: 1974,
    stock: 8,
    format: "LP",
    labelColor: "#B4562E",
    ringColor: "#5E2B14",
    description: "Horns that ache, a rhythm section that never rushes.",
  },
  {
    id: "wxw-005",
    title: "Loose Change",
    artist: "Benny Marrow",
    genre: "Funk",
    price: 22.0,
    year: 1981,
    stock: 15,
    format: "7\" Single",
    labelColor: "#C9A227",
    ringColor: "#6B5713",
    description: "Two minutes of pure pocket groove. Flip side is a stone classic.",
  },
  {
    id: "wxw-006",
    title: "The Long Corridor",
    artist: "Marchetti",
    genre: "Jazz",
    price: 64.0,
    year: 1965,
    stock: 2,
    format: "Box Set",
    labelColor: "#4A6A63",
    ringColor: "#233734",
    description: "Three-disc retrospective with unreleased alternate takes.",
  },
  {
    id: "wxw-007",
    title: "Paper Moths",
    artist: "Wilder June",
    genre: "Indie",
    price: 23.5,
    year: 2019,
    stock: 9,
    format: "LP",
    labelColor: "#9C6644",
    ringColor: "#4E3220",
    description: "Fragile, hand-picked melodies over tape hiss and room noise.",
  },
  {
    id: "wxw-008",
    title: "Signal Drift",
    artist: "Aperture Coast",
    genre: "Electronic",
    price: 29.0,
    year: 2023,
    stock: 5,
    format: "LP",
    labelColor: "#3E5C76",
    ringColor: "#1E2E3B",
    description: "Ambient textures built from field recordings and modular synth.",
  },
];
